/* Copyright 2026 Marimo. All rights reserved. */
/** biome-ignore-all lint/suspicious/noConsole: for debugging */
// @ts-check
import * as fs from "node:fs";
import openapiTS, { astToString, COMMENT_HEADER } from "openapi-typescript";

/**
 * Branded NewType schemas generated by the Python codegen post-processor.
 * Each key is the OpenAPI schema name; the value is the TypeScript brand tag.
 *
 * When a new NewType is added to marimo/_types/ids.py *and* registered in
 * _enrich_branded_types (commands.py), add a corresponding entry here so
 * the generated TypeScript carries the branded type.
 */
const BRANDED_TYPES = {
  Base64String: "Base64String",
  CellId: "CellId",
  SessionId: "SessionId",
  VariableName: "VariableName",
  RequestId: "RequestId",
  WidgetModelId: "WidgetModelId",
};

/**
 * Injected at the top of the generated file so branded schemas can reference it.
 */
const TYPED_STRING_HELPER =
  "/** Branded string type — compile-time only. */\ntype TypedString<T extends string> = string & { __brand: T };\n";

/**
 * Apply post-generation transforms to the TypeScript output.
 *
 * @param {string} content
 * @returns {string}
 */
function transform(content) {
  let result = content;

  // 1. Record<string, never> → Record<string, any>
  result = result.replace(/Record<string, never>/g, "Record<string, any>");

  // 2. Inject TypedString helper before the first export
  result = result.replace(/^(export )/m, `${TYPED_STRING_HELPER}\n$1`);

  // 3. Brand named type schemas.
  //    openapi-typescript emits these as top-level schema entries:
  //        SchemaName: string;
  //    We replace with:
  //        SchemaName: TypedString<"SchemaName">;
  for (const [schemaName, brand] of Object.entries(BRANDED_TYPES)) {
    const pattern = new RegExp(`(\\b${schemaName}): string;`);
    const replacement = `$1: TypedString<"${brand}">;`;
    result = result.replace(pattern, replacement);
  }

  // 4. UIElementId is a template literal, not a simple branded string.
  result = result.replace(
    /\bUIElementId: string;/,
    // biome-ignore lint/suspicious/noTemplateCurlyInString: there is no interpolation here, just raw string
    'UIElementId: `${components["schemas"]["CellId"]}-${string}`;',
  );

  return result;
}

async function main() {
  const source = new URL("./api.yaml", import.meta.url);
  const dest = new URL("./src/api.ts", import.meta.url);
  const nodes = await openapiTS(source, { defaultNonNullable: false });
  const content = transform(COMMENT_HEADER + astToString(nodes));
  fs.writeFileSync(dest, content);
  console.log("api.yaml → src/api.ts");
}

main();
