documentation:
  - changed-files:
      - any-glob-to-any-file: ['docs/**']
bash-focus:
  - changed-files:
      - any-glob-to-any-file: ['packages/openapi/api.yaml', 'frontend/index.html']
# Only valid once this is merged: https://github.com/actions/labeler/pull/866
# enhancement:
#   - title: ['^feat:', '^enhancement:']
# internal:
#   - title: ['^internal:', '^ci:']
# preview:
#   - title: ['^preview:', '^experimental:']
