fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint
        args: [-ignore, SC]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint-fix
        args: [-c, configs/.markdownlint.yaml, --fix, --disable, MD028]
        exclude: ^marimo/_tutorials/.*\.md

  - repo: https://github.com/crate-ci/typos
    rev: v1.43.1
    hooks:
      - id: typos
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # TODO: add back. this throws errors: thread 'tokio-rt-worker' (169) panicked at crates/oxc_allocator/src/pool/fixed_size.rs:112:67
  # - repo: https://github.com/oxc-project/mirrors-oxlint
  #   rev: v1.56.0
  #   hooks:
  #     - id: oxlint
  #       args: [--fix, --quiet]
  #       files: ^(frontend/src/|packages/)

  - repo: https://github.com/oxc-project/mirrors-oxfmt
    rev: v0.42.0
    hooks:
      - id: oxfmt
        args: [--write, --config, .oxfmtrc.json]
        files: ^(frontend/src/|packages/)
        "types_or": [javascript, jsx, ts, tsx]
