# 👋 This file was generated by marimo. You can edit it, and tweak
# things- just be conscious that some changes may be overwritten if opened in
# the editor. For instance top level imports are derived from a cell, and not
# the top of the script. This notice signifies the beginning of the generated
# import section.

import marimo  # noqa: I001

# Invert the order intentionally.
import pytest


__generated_with = "0.11.2"
app = marimo.App(_toplevel_fn=True)


@app.function
# Sanity check that base case works.
def add(a, b):
    return a + b


@app.function
@pytest.mark.parametrize(("a", "b", "c"), [(1, 1, 2), (1, 2, 3)])
def test_add_good(a, b, c):
    assert add(a, b) == c


@app.function
@pytest.mark.xfail(
    reason=("Check test is actually called."),
    raises=AssertionError,
    strict=True,
)
@pytest.mark.parametrize(("a", "b", "c"), [(1, 1, 3), (2, 2, 5)])
def test_add_bad(a, b, c):
    assert add(a, b) == c


@app.cell
def _():
    import marimo  # noqa: I001

    # Invert the order intentionally.
    import pytest
    return marimo, pytest


if __name__ == "__main__":
    app.run()
