# Note that marimo is not repeated in the imports.

import marimo

with marimo.import_guard():
    # Imports used by your notebook.
    # This section is automatically generated by marimo.
    import pytest


__generated_with = "0.0.0"
app = marimo.App(_toplevel_fn=True)


@app.function
# Sanity check that base case works.
def add(a, b):
    return a + b


@app.function
@pytest.mark.parametrize(("a", "b", "c"), [(1, 1, 2), (1, 2, 3)])
def test_add_good(a, b, c):
    assert add(a, b) == c


@app.function
@pytest.mark.xfail(
    reason=("Check test is actually called."),
    raises=AssertionError,
    strict=True,
)
@pytest.mark.parametrize(("a", "b", "c"), [(1, 1, 3), (2, 2, 5)])
def test_add_bad(a, b, c):
    assert add(a, b) == c


@app.cell
def _():
    # Invert the order intentionally.
    import pytest

    # Comments are stripped.
    import marimo  # noqa: I001

    # Final comments preserve total whitespace.
    return marimo, pytest


if __name__ == "__main__":
    app.run()
