/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * NotebookCell
     * @description Code cell specific structure
     */
    NotebookCell: {
      code: string | null;
      code_hash: string | null;
      config: components["schemas"]["NotebookCellConfig"];
      id: string | null;
      name: string | null;
    };
    /**
     * NotebookCellConfig
     * @description Configuration for a notebook cell
     */
    NotebookCellConfig: {
      column?: number | null;
      disabled?: boolean | null;
      hide_code?: boolean | null;
    };
    /**
     * NotebookMetadata
     * @description Metadata about the notebook
     */
    NotebookMetadata: {
      marimo_version?: string | null;
    };
    /**
     * NotebookV1
     * @description Main notebook structure
     */
    NotebookV1: {
      cells: components["schemas"]["NotebookCell"][];
      metadata: components["schemas"]["NotebookMetadata"];
      /** @enum {unknown} */
      version: "1";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
