# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-issue-forms.json
name: '📚 Documentation'
description: Suggest a change or new page to be added to docs.marimo.io
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this issue!
  - type: checkboxes
    id: documentation_is
    attributes:
      label: Documentation is
      options:
        - label: Missing
        - label: Outdated
        - label: Confusing
        - label: Not sure?
  - type: textarea
    id: description
    attributes:
      label: Explain in Detail
      description: A clear and concise description of your suggestion. If you intend to submit a PR for this issue, tell us in the description. Thanks!
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Your Suggestion for Changes
    validations:
      required: true
  - type: checkboxes
    id: will-submit-pr
    attributes:
      label: Will you submit a PR?
      description: |
        If you plan to submit a PR for this issue, please let us know. We'd love to review a PR!
      options:
        - label: 'Yes'
