# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-issue-forms.json
name: '🚀 New feature proposal'
description: Propose a new feature to be added to marimo
labels: [enhancement]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in marimo and sharing what features you would like to see!
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: 'Clear and concise description of the problem. Please make the reason and usecases as detailed as possible. If you intend to submit a PR for this issue, tell us in the description. Thanks!'
      placeholder: I am hoping to be able to...
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
    validations:
      required: true
  - type: checkboxes
    id: will-submit-pr
    attributes:
      label: Will you submit a PR?
      description: |
        If you plan to submit a PR for this issue, please let us know. We'd love to review a PR!
      options:
        - label: 'Yes'
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: "Clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
