# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-issue-forms.json
name: '🚀 New feature proposal'
description: Propose a new feature to be added to marimo
labels: [enhancement]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in marimo and sharing what features you would like to see!
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: 'A clear and concise description of the problem you are facing. Please describe your use case in detail. Thanks!'
      placeholder: I am hoping to be able to ...
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: 'What new feature or behavior would you like to see that would solve your problem? If possible, please provide an example of how the new feature would be used, or how the user experience would change. Thanks!'
    validations:
      required: true
  - type: checkboxes
    id: will-submit-pr
    attributes:
      label: Are you willing to submit a PR?
      description: |
        If you are interested in submitting a PR, please check this box.
        However, please confirm with us on whether your proposed feature
        fits with our roadmap before submitting a PR.
      options:
        - label: 'Yes'
  - type: textarea
    id: alternative
    attributes:
      label: Alternatives
      description: "Alternative solutions or features you've considered."
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
