/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    NotebookCell: {
      code: string | null;
      config: {
        column: number | null;
        disabled: boolean | null;
        hide_code: boolean | null;
      };
      id: string;
      name: string | null;
    };
    NotebookCellConfig: {
      column: number | null;
      disabled: boolean | null;
      hide_code: boolean | null;
    };
    NotebookMetadata: {
      marimo_version: string | null;
    };
    NotebookV1: {
      cells: components["schemas"]["NotebookCell"][];
      metadata: components["schemas"]["NotebookMetadata"];
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
