name: Install Repo
description: Checkout repo and install the ts toolchain and dependencies

runs:
  using: 'composite'

  steps:
    - name: ⎔ Setup pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

    - name: ⎔ Setup Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 24
        cache: pnpm
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: 📥 Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts --frozen-lockfile
