// Copyright 2026 Marimo. All rights reserved.
// deno-lint-ignore-file no-import-prefix

// Parse TS/CJS config files for token values that are not available as CSS.
import { parse as parseJavaScript } from "npm:@babel/parser@7.28.5";
import type {
  Expression,
  File,
  Node,
  ObjectExpression,
  ObjectProperty,
} from "npm:@babel/types@7.29.0";

// Normalize CSS colors, declarations, variables, functions, and calc() values.
import { formatHex, parse as parseColor } from "npm:culori@4.0.2";
import postcss from "npm:postcss@8.5.10";
import postcssCalc from "npm:postcss-calc@10.1.1";
import valueParser from "npm:postcss-value-parser@4.2.0";

// Reuse Tailwind's default scales and serialize the final DESIGN.md frontmatter.
import defaultTheme from "npm:tailwindcss@4.2.2/defaultTheme";
import { stringify as stringifyYaml } from "npm:yaml@2.8.3";

type TokenValue = string | TokenObject;
type TokenObject = { [key: string]: TokenValue };
type CssRoot = ReturnType<typeof postcss.parse>;
type ValueNode = ReturnType<typeof valueParser>["nodes"][number];
type FontSizeToken = string | [
  string,
  { lineHeight?: string; letterSpacing?: string; fontWeight?: string },
];
type TypographyParts = {
  fontFamily?: string;
  fontSize?: string;
  fontWeight?: string;
  lineHeight?: string;
  letterSpacing?: string;
};

const root = (Deno.args[0] ?? Deno.cwd()).replace(/\/+$/, "");
const generatedComment = "<!-- Generated by scripts/generate-design-md.ts. -->";

// Only primitive token sources are read; component guidance is kept hand-authored.
const sources = {
  appCss: "frontend/src/css/app/App.css",
  cellCss: "frontend/src/css/app/Cell.css",
  configSchema: "frontend/src/core/config/config-schema.ts",
  dataGridTheme: "frontend/src/plugins/impl/data-editor/themes.ts",
  globalCss: "frontend/src/css/globals.css",
  gridLayout: "frontend/src/components/editor/renderers/grid-layout/plugin.tsx",
  tailwindConfig: "frontend/tailwind.config.cjs",
} as const;

type SourceKey = keyof typeof sources;

// Keep the Tailwind default theme type narrow to the token families we emit.
const tailwindTheme = defaultTheme as unknown as {
  borderRadius: Record<string, string>;
  fontSize: Record<string, FontSizeToken>;
  fontWeight: Record<string, string>;
  letterSpacing: Record<string, string>;
  lineHeight: Record<string, string>;
  spacing: Record<string, string>;
};

// Hand-authored guidance complements generated tokens without mirroring UI code.
const body = [
  "## Intent",
  "",
  "marimo UI should feel compact, calm, readable, and native to a reactive notebook. Prefer clear controls, quiet surfaces, precise spacing, and useful output over decorative gradients or marketing layouts.",
  "",
  "## Token Use",
  "",
  "The YAML frontmatter is generated from marimo frontend tokens and layout defaults. Component entries are intentionally small: they are canonical examples, not a reverse-engineered inventory of every UI primitive.",
  "",
  "Use related token families for variants: hover, active, dark, destructive, error, success, stale, and visited states should derive from the same color families as their base component.",
  "",
  "## Components",
  "",
  "Buttons should use compact heights, label typography, md radius, and the primary, secondary, or action color families. Inputs should be compact, bordered, readable, and use code typography for code-like values.",
  "",
  "Notebook cells, outputs, code editors, and data views should be full-width, overflow-safe, and visually quieter than the controls around them.",
  "",
  "## UI Guidance",
  "",
  "- Use PT Sans for UI and prose, Lora for authored markdown headings, and Fira Mono for code-like values.",
  "- Keep controls compact and use generated tokens for sizing, radius, and semantic colors.",
  "- Use borders first and subtle shadows second. Avoid floating section cards and nested cards.",
  "- Reserve wider layouts for grids, dashboards, slides, and apps that need comparison or scanning.",
  "",
  "## Motion",
  "",
  "Use short, functional motion for state changes, loading, focus, and drag interactions. Avoid decorative animation.",
];

// Tuples are [CSS variable name, light token name, optional dark token name].
const colorSpecs = [
  ["background", "background", "background-dark"],
  ["foreground", "foreground", "foreground-dark"],
  ["muted", "surface-muted", "surface-muted-dark"],
  ["muted-foreground", "muted-foreground", "muted-foreground-dark"],
  ["popover", "popover", "popover-dark"],
  ["popover-foreground", "popover-foreground", "popover-foreground-dark"],
  ["card", "card", "card-dark"],
  ["card-foreground", "card-foreground", "card-foreground-dark"],
  ["border", "border", "border-dark"],
  ["input", "input", "input-dark"],
  ["primary", "primary", "primary-dark"],
  ["primary-foreground", "on-primary", "on-primary-dark"],
  ["secondary", "secondary", "secondary-dark"],
  ["secondary-foreground", "on-secondary", "on-secondary-dark"],
  ["accent", "accent", "accent-dark"],
  ["accent-foreground", "on-accent", "on-accent-dark"],
  ["ring", "ring"],
  ["destructive", "destructive"],
  ["destructive-foreground", "on-destructive"],
  ["error", "error"],
  ["error-foreground", "on-error"],
  ["success", "success"],
  ["success-foreground", "on-success"],
  ["action", "action"],
  ["action-hover", "action-hover"],
  ["action-foreground", "on-action"],
  ["link", "link", "link-dark"],
  ["link-visited", "link-visited", "link-visited-dark"],
  ["stale", "stale"],
  ["cm-background", "code-background", "code-background-dark"],
] as const;

const cssCache = new Map<SourceKey, CssRoot>();
const cssVarCache = new Map<SourceKey, Record<string, string>>();
const astCache = new Map<SourceKey, File>();

// The optional first arg lets CI run from any cwd while defaulting to repo root.
const repoPath = (relativePath: string) =>
  root ? `${root}/${relativePath}` : relativePath;
const read = (relativePath: string) =>
  Deno.readTextFileSync(repoPath(relativePath));
const readSource = (source: SourceKey) => read(sources[source]);
// DESIGN.md references tokens with {group.name} strings.
const tokenRef = (group: string, name: string) => `{${group}.${name}}`;
const colorRef = (name: string) => tokenRef("colors", name);
const roundedRef = (name: string) => tokenRef("rounded", name);
const typographyRef = (name: string) => tokenRef("typography", name);

// Parsed CSS and ASTs are shared across token builders.
const cached = <K, V>(cache: Map<K, V>, key: K, build: () => V): V => {
  const value = cache.get(key);
  if (value) {
    return value;
  }
  const next = build();
  cache.set(key, next);
  return next;
};

const cleanCss = (value: string) => value.trim().replace(/\s+/g, " ");

const required = <T>(value: T | undefined, label: string): T => {
  if (value === undefined || value === null || value === "") {
    throw new Error(`Could not find ${label}`);
  }
  return value;
};

const cssRoot = (source: SourceKey) =>
  cached(
    cssCache,
    source,
    () => postcss.parse(readSource(source), { from: sources[source] }),
  );

// Collect custom properties without the leading "--".
const cssVars = (source: SourceKey): Record<string, string> =>
  cached(cssVarCache, source, () => {
    const vars: Record<string, string> = {};
    cssRoot(source).walkDecls((decl) => {
      if (decl.prop.startsWith("--")) {
        vars[decl.prop.slice("--".length)] = cleanCss(decl.value);
      }
    });
    return vars;
  });

// Direct CSS reads are reserved for notebook layout facts owned by CSS.
const cssDeclaration = (
  source: SourceKey,
  selector: string,
  property: string,
) => {
  let value: string | undefined;
  cssRoot(source).walkRules((rule) => {
    if (rule.selector === selector) {
      rule.walkDecls(property, (decl) => {
        value ??= cleanCss(decl.value);
      });
    }
  });
  return required(value, `${source}:${selector}:${property}`);
};

// Split CSS function nodes such as var(...) and light-dark(...) by arguments.
const functionArgs = (node: ValueNode) => {
  if (node.type !== "function") {
    throw new Error("Expected CSS function node");
  }
  const args: ValueNode[][] = [[]];
  for (const child of node.nodes) {
    if (child.type === "div" && child.value === ",") {
      args.push([]);
    } else {
      args.at(-1)?.push(child);
    }
  }
  return args.map((nodes) => valueParser.stringify(nodes).trim());
};

const singleFunction = (value: string) => {
  const nodes = valueParser(value).nodes.filter((node) =>
    node.type !== "space"
  );
  return nodes.length === 1 && nodes[0].type === "function"
    ? nodes[0]
    : undefined;
};

// Resolve var(...) and light-dark(...) into concrete hex colors for DESIGN.md.
const resolveColorValue = (
  value: string,
  vars: Record<string, string>,
  mode: "light" | "dark",
  seen = new Set<string>(),
): string => {
  const normalized = cleanCss(value);
  const fn = singleFunction(normalized);
  if (fn?.value === "light-dark") {
    const [light, dark] = functionArgs(fn);
    return resolveColorValue(mode === "light" ? light : dark, vars, mode, seen);
  }
  if (fn?.value === "var") {
    const [nameArg, fallback] = functionArgs(fn);
    const name = nameArg.replace(/^--/, "");
    if (seen.has(name)) {
      throw new Error(`Cycle while resolving --${name}`);
    }
    seen.add(name);
    return resolveColorValue(
      required(vars[name] ?? fallback, `--${name}`),
      vars,
      mode,
      seen,
    );
  }
  return formatHex(required(parseColor(normalized), normalized)).toUpperCase();
};

// Inline var(...) before postcss-calc reduces dimensions.
const inlineCssVars = (value: string, vars = cssVars("globalCss")) => {
  const parsed = valueParser(value);
  parsed.walk((node) => {
    if (node.type === "function" && node.value === "var") {
      const [name] = functionArgs(node);
      Object.assign(node as ValueNode & { type: string; value: string }, {
        type: "word",
        value: required(vars[name.replace(/^--/, "")], name),
      });
    }
  });
  return parsed.toString();
};

// Normalize calc(...) and CSS variables to stable scalar dimensions.
const reduceDimension = (value: string) => {
  const result = postcss([postcssCalc({})]).process(
    `:root{x:${inlineCssVars(value)}}`,
    { from: undefined },
  );
  let reduced: string | undefined;
  result.root.walkDecls("x", (decl) => {
    reduced = decl.value;
  });
  return cleanCss(required(reduced, value));
};

// Parse TS only for config/grid constants, not for UI component extraction.
const ast = (source: SourceKey) =>
  cached(astCache, source, () =>
    parseJavaScript(readSource(source), {
      sourceType: "unambiguous",
      plugins: ["jsx", "typescript"],
    }));

const isNode = (value: unknown): value is Node =>
  typeof value === "object" && value !== null &&
  typeof (value as { type?: unknown }).type === "string";

// Tiny AST walker avoids pulling in a full Babel traversal dependency.
const walkAst = (value: unknown, visit: (node: Node) => void): void => {
  if (Array.isArray(value)) {
    value.forEach((child) => walkAst(child, visit));
    return;
  }
  if (!isNode(value)) {
    return;
  }
  visit(value);
  for (const [key, child] of Object.entries(value)) {
    if (
      !key.endsWith("Comments") &&
      !["loc", "start", "end", "extra"].includes(key)
    ) {
      walkAst(child, visit);
    }
  }
};

const propName = (name: ObjectProperty["key"]) => {
  if (name.type === "Identifier") {
    return name.name;
  }
  if (name.type === "StringLiteral") {
    return name.value;
  }
  if (name.type === "NumericLiteral") {
    return String(name.value);
  }
};

const objectProperty = (
  object: ObjectExpression,
  name: string,
): Expression | undefined => {
  for (const property of object.properties) {
    if (property.type === "ObjectProperty" && propName(property.key) === name) {
      return property.value as Expression;
    }
  }
};

const objectPath = (
  object: ObjectExpression,
  path: readonly string[],
): Expression | undefined =>
  path.reduce<Expression | undefined>(
    (current, segment) =>
      current?.type === "ObjectExpression"
        ? objectProperty(current, segment)
        : undefined,
    object,
  );

// Evaluate the small expression subset used by Tailwind/grid config constants.
const numericExpression = (expression: Expression): number | undefined => {
  if (expression.type === "NumericLiteral") {
    return expression.value;
  }
  if (
    expression.type === "BinaryExpression" &&
    expression.operator === "/" &&
    expression.left.type !== "PrivateName"
  ) {
    const left = numericExpression(expression.left);
    const right = numericExpression(expression.right);
    return left !== undefined && right !== undefined ? left / right : undefined;
  }
};

// Convert string, number, and simple template literals to token strings.
const expressionText = (expression: Expression): string | undefined => {
  if (expression.type === "StringLiteral") {
    return expression.value;
  }
  if (expression.type === "NumericLiteral") {
    return String(expression.value);
  }
  if (expression.type === "TemplateLiteral") {
    const nested = expression.expressions[0];
    const value = nested && !nested.type.startsWith("TS")
      ? numericExpression(nested as Expression)
      : undefined;
    return value !== undefined && expression.expressions.length === 1
      ? `${Number(value.toFixed(5))}${
        expression.quasis[1]?.value.cooked ?? expression.quasis[1]?.value.raw ??
          ""
      }`
      : undefined;
  }
};

// Read nested values from frontend/tailwind.config.cjs.
const configValue = (path: readonly string[]) => {
  let value: string | undefined;
  walkAst(ast("tailwindConfig"), (node) => {
    if (value || node.type !== "ObjectExpression") {
      return;
    }
    const expression = objectPath(node, path);
    value = expression ? expressionText(expression) : undefined;
  });
  return required(value, path.join("."));
};

// Pull numeric layout defaults from renderer object literals.
const numericProperty = (source: SourceKey, key: string) => {
  let value: number | undefined;
  walkAst(ast(source), (node) => {
    if (value !== undefined || node.type !== "ObjectProperty") {
      return;
    }
    const expression = propName(node.key) === key ? node.value : undefined;
    value = expression
      ? numericExpression(expression as Expression)
      : undefined;
  });
  return required(value, `${source}:${key}`);
};

const themePath = (path: readonly string[]) =>
  path.reduce<unknown>(
    (current, key) =>
      current && typeof current === "object"
        ? (current as Record<string, unknown>)[key]
        : undefined,
    tailwindTheme,
  );

const themeString = (path: readonly string[]) =>
  String(required(themePath(path), path.join(".")));

// Font CSS vars wrap a var(...) fallback chain; the quoted fallback is the name.
const fontName = (familyVar: string) => {
  const value = cssVars("globalCss")[familyVar];
  const node = value
    ? valueParser(value).nodes.find((part) =>
      part.type === "function" && part.value === "var"
    )
    : undefined;
  const fallback = node ? functionArgs(node).slice(1).join() : value;
  return required(
    valueParser(required(fallback, familyVar)).nodes.find((part) =>
      part.type === "string"
    )?.value,
    familyVar,
  );
};

const fontSizeToken = (name: string): TypographyParts => {
  const token = required(tailwindTheme.fontSize[name], `fontSize.${name}`);
  if (typeof token === "string") {
    return { fontSize: token };
  }
  return Object.fromEntries(
    Object.entries({
      fontSize: token[0],
      lineHeight: token[1].lineHeight,
      letterSpacing: token[1].letterSpacing,
      fontWeight: token[1].fontWeight,
    }).filter(([, value]) => value),
  ) as TypographyParts;
};

// Config schema defaults are regex-read because the zod chain is not exported.
const configDefault = (field: string) => {
  const pattern = new RegExp(
    `${field}:\\s*z\\.number\\(\\)\\.nonnegative\\(\\)\\.prefault\\((\\d+)\\)`,
  );
  return required(readSource("configSchema").match(pattern)?.[1], field);
};

// Shared constructor for Tailwind-backed typography tokens.
const typographyToken = (
  {
    family,
    size,
    fontSize,
    weight = "normal",
    lineHeight,
    letterSpacing = "normal",
  }: {
    family: string;
    size: string;
    fontSize?: string;
    weight?: string;
    lineHeight?: string;
    letterSpacing?: string;
  },
): Required<TypographyParts> => {
  const sizeParts = fontSizeToken(size);
  return {
    fontFamily: fontName(family),
    fontSize: fontSize ?? required(sizeParts.fontSize, `fontSize.${size}`),
    fontWeight: sizeParts.fontWeight ??
      required(tailwindTheme.fontWeight[weight], `fontWeight.${weight}`),
    lineHeight: lineHeight
      ? themeString(["lineHeight", lineHeight])
      : required(sizeParts.lineHeight, `lineHeight.${size}`),
    letterSpacing: sizeParts.letterSpacing ??
      themeString(["letterSpacing", letterSpacing]),
  };
};

// Mirror the frontend CSS variable color set, plus semantic aliases.
const buildColors = () => {
  const vars = cssVars("globalCss");
  const colors: Record<string, string> = {};
  for (const [cssName, lightName, darkName] of colorSpecs) {
    colors[lightName] = resolveColorValue(
      required(vars[cssName], cssName),
      vars,
      "light",
    );
    if (darkName) {
      colors[darkName] = resolveColorValue(
        required(vars[cssName], cssName),
        vars,
        "dark",
      );
    }
  }

  // Surface aliases are agent-facing names for existing background/card tokens.
  colors.surface = required(colors.background, "surface");
  colors["surface-dark"] = required(
    colors["card-dark"] ?? colors["background-dark"],
    "surface-dark",
  );
  // The data grid accent is a TS literal, not a CSS custom property.
  colors["data-grid-accent"] = formatHex(
    required(
      parseColor(
        required(
          readSource("dataGridTheme").match(/accentColor:\s*"([^"]+)"/)?.[1],
          "data-grid-accent",
        ),
      ),
      "data-grid-accent",
    ),
  ).toUpperCase();

  return colors;
};

// Keep typography to canonical agent-facing scales, not every UI text variant.
const buildTypography = () => ({
  "body-md": typographyToken({
    family: "text-font",
    size: "base",
    lineHeight: "7",
  }),
  "body-sm": typographyToken({ family: "text-font", size: "sm" }),
  "label-md": typographyToken({
    family: "text-font",
    size: "sm",
    weight: "medium",
    lineHeight: "none",
  }),
  "label-xs": typographyToken({
    family: "text-font",
    size: "xs",
    weight: "semibold",
  }),
  "markdown-heading": typographyToken({
    family: "heading-font",
    size: "3xl",
    weight: "semibold",
    letterSpacing: "tight",
  }),
  "code-editor": typographyToken({
    family: "monospace-font",
    size: "sm",
    fontSize: `${configDefault("code_editor_font_size")}px`,
  }),
  "slide-h1": {
    fontFamily: fontName("text-font"),
    fontSize: configValue([
      "theme",
      "extend",
      "typography",
      "slides",
      "css",
      "h1",
      "fontSize",
    ]),
    fontWeight: required(tailwindTheme.fontWeight.semibold, "semibold"),
    lineHeight: configValue([
      "theme",
      "extend",
      "typography",
      "slides",
      "css",
      "h1",
      "lineHeight",
    ]),
    letterSpacing: themeString(["letterSpacing", "normal"]),
  },
});

// Radius tokens mix Tailwind defaults, Tailwind overrides, and cell CSS.
const buildRounded = () => ({
  sm: reduceDimension(configValue(["theme", "extend", "borderRadius", "sm"])),
  DEFAULT: reduceDimension(required(cssVars("globalCss").radius, "radius")),
  md: reduceDimension(configValue(["theme", "extend", "borderRadius", "md"])),
  lg: reduceDimension(configValue(["theme", "extend", "borderRadius", "lg"])),
  cell: reduceDimension(
    cssDeclaration("cellCss", ".marimo-cell", "border-radius"),
  ),
  xl: themeString(["borderRadius", "xl"]),
  full: themeString(["borderRadius", "full"]),
});

// Spacing includes Tailwind scale values plus notebook layout dimensions.
const buildSpacing = () => ({
  unit: themeString(["spacing", "2"]),
  xs: themeString(["spacing", "1"]),
  sm: themeString(["spacing", "2"]),
  md: themeString(["spacing", "4"]),
  lg: themeString(["spacing", "6"]),
  xl: themeString(["spacing", "12"]),
  "content-compact": required(cssVars("appCss")["content-width"], "content"),
  "content-medium": required(
    cssVars("appCss")["content-width-medium"],
    "content-medium",
  ),
  "content-wide": `${numericProperty("gridLayout", "maxWidth")}px`,
  "grid-row-height": `${numericProperty("gridLayout", "rowHeight")}px`,
  // String form avoids design.md treating this unitless count as a raw number.
  "grid-columns": String(numericProperty("gridLayout", "columns")),
});

// Canonical examples only; prose guidance covers the larger component family.
const buildComponents = () => ({
  "app-shell": {
    backgroundColor: colorRef("background"),
    textColor: colorRef("foreground"),
    typography: typographyRef("body-md"),
  },
  cell: {
    backgroundColor: colorRef("surface"),
    textColor: colorRef("foreground"),
    typography: typographyRef("body-md"),
    rounded: roundedRef("cell"),
    width: cssDeclaration("cellCss", ".marimo-cell", "width"),
  },
  "output-area": {
    backgroundColor: colorRef("surface"),
    textColor: colorRef("foreground"),
    typography: typographyRef("body-md"),
    padding: cssDeclaration("cellCss", ".output-area", "padding"),
    width: cssDeclaration("cellCss", ".output-area", "width"),
  },
  "code-editor": {
    backgroundColor: colorRef("code-background"),
    textColor: colorRef("foreground"),
    typography: typographyRef("code-editor"),
    width: cssDeclaration("cellCss", ".cm", "width"),
  },
  "button-primary": {
    backgroundColor: colorRef("primary"),
    textColor: colorRef("on-primary"),
    typography: typographyRef("label-md"),
    rounded: roundedRef("md"),
    height: themeString(["spacing", "9"]),
  },
  "button-action": {
    backgroundColor: colorRef("action"),
    textColor: colorRef("on-action"),
    typography: typographyRef("label-md"),
    rounded: roundedRef("md"),
    height: themeString(["spacing", "9"]),
  },
  input: {
    backgroundColor: colorRef("background"),
    textColor: colorRef("foreground"),
    typography: typographyRef("code-editor"),
    rounded: roundedRef("sm"),
    height: themeString(["spacing", "6"]),
  },
  "data-table": {
    backgroundColor: colorRef("surface"),
    textColor: colorRef("foreground"),
    typography: typographyRef("body-sm"),
    width: "100%",
  },
});

// YAML frontmatter is generated; markdown body is appended below it.
const tokens = () => ({
  version: "alpha",
  name: "marimo",
  description:
    "Design system for marimo, a reactive Python notebook for reproducible, git-friendly, deployable work.",
  colors: buildColors(),
  typography: buildTypography(),
  rounded: buildRounded(),
  spacing: buildSpacing(),
  components: buildComponents(),
});

const renderDesignMd = () =>
  `---\n${
    stringifyYaml(tokens(), { lineWidth: 0 })
  }---\n\n${generatedComment}\n\n${body.join("\n")}\n`;

// Print the artifact so Make/CI can either write it or diff it without mutation.
Deno.stdout.writeSync(new TextEncoder().encode(renderDesignMd()));
