[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = []
name = "marimo_docs"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
include = ["blocks.py"]
