name: 🏷️ Pull Request Labeler

# Auto-label pull requests based on config in .github/labeler.yml

on:
  pull_request_target:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
