name: GitHub Pages

on:
  # Weekly
  schedule:
    - cron: "0 0 * * 0" # Run at midnight UTC on Sunday

  # Allow manual trigger
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_SYSTEM_PYTHON: 1
  UV_EXCLUDE_NEWER: "7 days"

jobs:
  export-notebooks:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: 🐍 Setup uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: true
          python-version: 3.12

      - name: 🛠️ Run export
        run: |
          uvx marimo export html-wasm frontend/public/files/wasm-intro.py -o out --mode run
          sed -i -e "s/after_delay/off/g" out/index.html

      - name: 📄 List changed files
        continue-on-error: true
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD

      - name: 📦 Upload Pages Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: out

  deploy:
    needs: export-notebooks
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: 🌐 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        with:
          artifact_name: github-pages
