name: Test Pre-built Wheel

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test_no_build.yaml
      - pyproject.toml
      - marimo/_cli/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test_no_build.yaml
      - pyproject.toml
      - marimo/_cli/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv build --wheel
          WHEEL=$(ls dist/*.whl)
          uv tool run --no-build --python=${{ matrix.python-version }} --from "$WHEEL" marimo --version
